#!/usr/bin/env bash
# Transfers a file from our client to a server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

# check if the number of of args is less than 4

if [ "$#" -ne 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"

exit $?
