#!/usr/bin/env bash
# Installs nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
#sudo touch /var/www/html/index.html
#sudo rm /var/www/html/index.nginx-debian.html
sudo chown ubuntu:ubuntu -R /var/www/html
sudo rm /var/www/html/index.nginx-debian.html
echo "Holberton School" > /var/www/html/index.html
sudo service nginx restart
~

