#!/usr/bin/env bash
# Configuring Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

# Redirection configuration
replacement="server_name _;\\
    location /redirect_me {\\
        return 301 https://github.com/noel-odero/;\\
    }"
sudo sed -i "s|server_name _;|$replacement|" /etc/nginx/sites-available/default

sudo nginx -t
sudo service nginx restart
